### PR TITLE
Improve theme

### PR DESCRIPTION
**Pull request by elyezer**
* Add featured image plugin and update all posts to use it
* Set LOCALE to localize dates and other text
* Move the logo image to the top banner
* Improve main page's post listing
* Improve post detail page style
* Translate Archives to pt_BR
* Add icons to the post meta data info
* Centralize pagination

Took some screenshots:

screenshot from 2017-04-16 12-30-41
screenshot from 2017-04-16 12-30-53
screenshot from 2017-04-16 12-31-16

### CODE REVIEW

**Comment by omaciel** [comment]
Acho que pode mandar bala

**Comment by omaciel** [comment]
@elyezer 

```shell
$ python --version
Python 2.7.9
$ pip --version
pip 6.0.7 from /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages (python 2.7)
install
64.89s$ pip install -r requirements.txt
Collecting Jinja2==2.7.3 (from -r requirements.txt (line 2))
  Downloading Jinja2-2.7.3.tar.gz (378kB)
    100% |################################| 380kB 1.7MB/s 
Collecting Markdown==2.5.2 (from -r requirements.txt (line 3))
  Downloading Markdown-2.5.2.zip (401kB)
    100% |################################| 405kB 1.5MB/s 
Collecting MarkupSafe==0.23 (from -r requirements.txt (line 4))
  Downloading MarkupSafe-0.23.tar.gz
Collecting Pygments==2.0.1 (from -r requirements.txt (line 5))
  Downloading Pygments-2.0.1-py2-none-any.whl (672kB)
    100% |################################| 675kB 853kB/s 
Collecting Unidecode==0.04.16 (from -r requirements.txt (line 6))
  Downloading Unidecode-0.04.16.tar.gz (200kB)
    100% |################################| 200kB 2.7MB/s 
    /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/setuptools/dist.py:283: UserWarning: The version specified requires normalization, consider using '0.4.16' instead of '0.04.16'.
      self.metadata.version,
Collecting beautifulsoup4==4.3.2 (from -r requirements.txt (line 7))
  Downloading beautifulsoup4-4.3.2.tar.gz (143kB)
    100% |################################| 143kB 3.6MB/s 
Collecting blinker==1.3 (from -r requirements.txt (line 8))
  Downloading blinker-1.3.tar.gz (91kB)
    100% |################################| 94kB 5.1MB/s 
Collecting docutils==0.12 (from -r requirements.txt (line 9))
  Downloading docutils-0.12.tar.gz (1.6MB)
    100% |################################| 1.6MB 362kB/s 
Collecting feedgenerator==1.7 (from -r requirements.txt (line 10))
  Downloading feedgenerator-1.7.tar.gz
Collecting ghp-import==0.4.1 (from -r requirements.txt (line 11))
  Downloading ghp-import-0.4.1.tar.gz
Collecting lxml==3.4.1 (from -r requirements.txt (line 12))
  Downloading lxml-3.4.1.tar.gz (3.5MB)
    100% |################################| 3.5MB 163kB/s 
    /opt/python/2.7.9/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    Building lxml version 3.4.1.
    Building without Cython.
    Using build configuration of libxslt 1.1.26
    Building against libxml2/libxslt in the following directory: /usr/lib/x86_64-linux-gnu
Collecting pelican==3.5.0 (from -r requirements.txt (line 13))
  Downloading pelican-3.5.0-py2.py3-none-any.whl (514kB)
    100% |################################| 516kB 1.2MB/s 
Collecting python-dateutil==2.2 (from -r requirements.txt (line 14))
  Downloading python-dateutil-2.2.tar.gz (259kB)
    100% |################################| 262kB 2.2MB/s 
Collecting pytz==2014.9 (from -r requirements.txt (line 15))
  Downloading pytz-2014.9-py2.py3-none-any.whl (477kB)
    100% |################################| 479kB 1.0MB/s 
Collecting six==1.8.0 (from -r requirements.txt (line 16))
  Downloading six-1.8.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): wsgiref==0.1.2 in /opt/python/2.7.9/lib/python2.7 (from -r requirements.txt (line 17))
Installing collected packages: six, pytz, python-dateutil, pelican, lxml, ghp-import, feedgenerator, docutils, blinker, beautifulsoup4, Unidecode, Pygments, MarkupSafe, Markdown, Jinja2
  Running setup.py install for python-dateutil
  Running setup.py install for lxml
    /opt/python/2.7.9/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    Building lxml version 3.4.1.
    Building without Cython.
    Using build configuration of libxslt 1.1.26
    Building against libxml2/libxslt in the following directory: /usr/lib/x86_64-linux-gnu
    building 'lxml.etree' extension
    gcc -pthread -fno-strict-aliasing -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/include/libxml2 -I/tmp/pip-build-mkdGsE/lxml/src/lxml/includes -I/opt/python/2.7.9/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w
    gcc -pthread -shared -L/opt/python/2.7.9/lib -Wl,-rpath=/opt/python/2.7.9/lib build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -L/usr/lib/x86_64-linux-gnu -L/opt/python/2.7.9/lib -lxslt -lexslt -lxml2 -lz -lm -lpython2.7 -o build/lib.linux-x86_64-2.7/lxml/etree.so
    building 'lxml.objectify' extension
    gcc -pthread -fno-strict-aliasing -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/include/libxml2 -I/tmp/pip-build-mkdGsE/lxml/src/lxml/includes -I/opt/python/2.7.9/include/python2.7 -c src/lxml/lxml.objectify.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.objectify.o -w
    gcc -pthread -shared -L/opt/python/2.7.9/lib -Wl,-rpath=/opt/python/2.7.9/lib build/temp.linux-x86_64-2.7/src/lxml/lxml.objectify.o -L/usr/lib/x86_64-linux-gnu -L/opt/python/2.7.9/lib -lxslt -lexslt -lxml2 -lz -lm -lpython2.7 -o build/lib.linux-x86_64-2.7/lxml/objectify.so
  Running setup.py install for ghp-import
    changing mode of build/scripts-2.7/ghp-import from 644 to 755
    changing mode of /home/travis/virtualenv/python2.7.9/bin/ghp-import to 755
  Running setup.py install for feedgenerator
  Running setup.py install for docutils
    changing mode of build/scripts-2.7/rst2html.py from 644 to 755
    changing mode of build/scripts-2.7/rst2s5.py from 644 to 755
    changing mode of build/scripts-2.7/rst2latex.py from 644 to 755
    changing mode of build/scripts-2.7/rst2xetex.py from 644 to 755
    changing mode of build/scripts-2.7/rst2man.py from 644 to 755
    changing mode of build/scripts-2.7/rst2xml.py from 644 to 755
    changing mode of build/scripts-2.7/rst2pseudoxml.py from 644 to 755
    changing mode of build/scripts-2.7/rstpep2html.py from 644 to 755
    changing mode of build/scripts-2.7/rst2odt.py from 644 to 755
    changing mode of build/scripts-2.7/rst2odt_prepstyles.py from 644 to 755
    changing mode of /home/travis/virtualenv/python2.7.9/bin/rst2html.py to 755
    changing mode of /home/travis/virtualenv/python2.7.9/bin/rst2s5.py to 755
    changing mode of /home/travis/virtualenv/python2.7.9/bin/rst2latex.py to 755
    changing mode of /home/travis/virtualenv/python2.7.9/bin/rst2xetex.py to 755
    changing mode of /home/travis/virtualenv/python2.7.9/bin/rst2man.py to 755
    changing mode of /home/travis/virtualenv/python2.7.9/bin/rst2xml.py to 755
    changing mode of /home/travis/virtualenv/python2.7.9/bin/rst2pseudoxml.py to 755
    changing mode of /home/travis/virtualenv/python2.7.9/bin/rstpep2html.py to 755
    changing mode of /home/travis/virtualenv/python2.7.9/bin/rst2odt.py to 755
    changing mode of /home/travis/virtualenv/python2.7.9/bin/rst2odt_prepstyles.py to 755
  Running setup.py install for blinker
  Running setup.py install for beautifulsoup4
  Running setup.py install for Unidecode
    /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/setuptools/dist.py:283: UserWarning: The version specified requires normalization, consider using '0.4.16' instead of '0.04.16'.
      self.metadata.version,
  Running setup.py install for MarkupSafe
    building 'markupsafe._speedups' extension
    gcc -pthread -fno-strict-aliasing -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/python/2.7.9/include/python2.7 -c markupsafe/_speedups.c -o build/temp.linux-x86_64-2.7/markupsafe/_speedups.o
    gcc -pthread -shared -L/opt/python/2.7.9/lib -Wl,-rpath=/opt/python/2.7.9/lib build/temp.linux-x86_64-2.7/markupsafe/_speedups.o -L/opt/python/2.7.9/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/markupsafe/_speedups.so
  Running setup.py install for Markdown
    changing mode of build/scripts-2.7/markdown_py from 644 to 755
    Converting docs/index.txt -> build/docs/index.html
    Converting docs/release-2.4.txt -> build/docs/release-2.4.html
    Converting docs/siteindex.txt -> build/docs/siteindex.html
    Converting docs/release-2.0.2.txt -> build/docs/release-2.0.2.html
    Converting docs/release-2.3.txt -> build/docs/release-2.3.html
    Converting docs/install.txt -> build/docs/install.html
    Converting docs/release-2.0.1.txt -> build/docs/release-2.0.1.html
    Converting docs/release-2.0.txt -> build/docs/release-2.0.html
    Converting docs/release-2.2.1.txt -> build/docs/release-2.2.1.html
    Converting docs/release-2.1.0.txt -> build/docs/release-2.1.0.html
    Converting docs/release-2.1.1.txt -> build/docs/release-2.1.1.html
    Converting docs/cli.txt -> build/docs/cli.html
    Converting docs/authors.txt -> build/docs/authors.html
    Converting docs/release-2.2.0.txt -> build/docs/release-2.2.0.html
    Converting docs/reference.txt -> build/docs/reference.html
    Converting docs/release-2.5.txt -> build/docs/release-2.5.html
    Converting docs/test_suite.txt -> build/docs/test_suite.html
    Converting docs/change_log.txt -> build/docs/change_log.html
    Converting docs/extensions/index.txt -> build/docs/extensions/index.html
    Converting docs/extensions/footnotes.txt -> build/docs/extensions/footnotes.html
    Converting docs/extensions/definition_lists.txt -> build/docs/extensions/definition_lists.html
    Converting docs/extensions/wikilinks.txt -> build/docs/extensions/wikilinks.html
    Converting docs/extensions/header_id.txt -> build/docs/extensions/header_id.html
    Converting docs/extensions/attr_list.txt -> build/docs/extensions/attr_list.html
    Converting docs/extensions/meta_data.txt -> build/docs/extensions/meta_data.html
    Converting docs/extensions/api.txt -> build/docs/extensions/api.html
    Converting docs/extensions/fenced_code_blocks.txt -> build/docs/extensions/fenced_code_blocks.html
    Converting docs/extensions/sane_lists.txt -> build/docs/extensions/sane_lists.html
    Converting docs/extensions/abbreviations.txt -> build/docs/extensions/abbreviations.html
    Converting docs/extensions/code_hilite.txt -> build/docs/extensions/code_hilite.html
    Converting docs/extensions/tables.txt -> build/docs/extensions/tables.html
    Converting docs/extensions/toc.txt -> build/docs/extensions/toc.html
    Converting docs/extensions/smarty.txt -> build/docs/extensions/smarty.html
    Converting docs/extensions/admonition.txt -> build/docs/extensions/admonition.html
    Converting docs/extensions/smart_strong.txt -> build/docs/extensions/smart_strong.html
    Converting docs/extensions/nl2br.txt -> build/docs/extensions/nl2br.html
    Converting docs/extensions/extra.txt -> build/docs/extensions/extra.html
    changing mode of /home/travis/virtualenv/python2.7.9/bin/markdown_py to 755
  Running setup.py install for Jinja2
Successfully installed Jinja2-2.7.3 Markdown-2.5.2 MarkupSafe-0.23 Pygments-2.0.1 Unidecode-0.4.16 beautifulsoup4-4.3.2 blinker-1.3 docutils-0.12 feedgenerator-1.7 ghp-import-0.4.1 lxml-3.4.1 pelican-3.5.0 python-dateutil-2.2 pytz-2014.9 six-1.8.0
0.23s$ make publish travis
pelican /home/travis/build/CastalioPodcast/CastalioPodcast.github.io/content -o /home/travis/build/CastalioPodcast/CastalioPodcast.github.io/output -s /home/travis/build/CastalioPodcast/CastalioPodcast.github.io/publishconf.py 
WARNING: LOCALE option doesn't contain a correct value
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/bin/pelican", line 11, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pelican/__init__.py", line 351, in main
    pelican, settings = get_instance(args)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pelican/__init__.py", line 345, in get_instance
    return cls(settings), settings
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pelican/__init__.py", line 56, in __init__
    self.init_plugins()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pelican/__init__.py", line 83, in init_plugins
    plugin.register()
  File "/home/travis/build/CastalioPodcast/CastalioPodcast.github.io/plugins/featured_image/featured_image.py", line 28, in register
    signals.all_generators_finalized.connect(run_plugin)
AttributeError: 'module' object has no attribute 'all_generators_finalized'
make: *** [publish] Error 1
The command "make publish travis" exited with 2.
```

**Comment by rochacbruno** [comment]
@elyezer @omaciel o menu `sobre` sumiu. Foi removido mesmo ou é bug?

**Comment by elyezer** [comment]
@rochacbruno vou dar uma olhada, nao era para ter sumido.

**Comment by elyezer** [comment]
@rochacbruno https://github.com/CastalioPodcast/CastalioPodcast.github.io/pull/90 vai corrigir o problema com as paginas.

**Pull request merged**
