### PR TITLE
Revision text - fixed minor typos

### PR DESCRIPTION
**Pull request by vsvsbr**
Changes:
- line 15 - finalmente --> **enfim**
- line 32 - sento --> **sinto**
- line 36 - lentos --> **lento**  ... requere --> **requer**
- line 40 - veredicto --> **veredito** ... +**em** _dezembro_ ... +**em que** _eu li o livro_ 
- line 48 - está --> **estão** .... duplo --> **dupla**

I hope this will help you. ;)

### CODE REVIEW

**Comment by omaciel** [comment]
Thank you so much for this!!! :) I will merge it right away.

**Comment by omaciel** [comment]
@vsvsbr merged your changes (thank you again) and also made 2 more changes, which can be seen here: https://github.com/CastalioPodcast/CastalioPodcast.github.io/commit/9897fa05ff823917adab066af0341a85a06896b8

**Comment by elyezer** [comment]
:+1:

**Comment by vsvsbr** [comment]
:clap: :smile: thanks!

**Pull request merged**
